### ISSUE TITLE
Failure to autodetect package names in (some) multi-project repositories

### ISSUE THREAD

**Issue by dividedmind** [getappmap/appmap-java#283]
I tried using appmap-java with https://github.com/square/retrofit which is structured like this:
```console
$ find |grep 'src/main$'
./retrofit-adapters/guava/src/main
./retrofit-adapters/java8/src/main
./retrofit-adapters/rxjava/src/main
./retrofit-adapters/rxjava2/src/main
./retrofit-adapters/rxjava3/src/main
./retrofit-adapters/scala/src/main
./retrofit-converters/gson/src/main
./retrofit-converters/guava/src/main
./retrofit-converters/jackson/src/main
./retrofit-converters/java8/src/main
./retrofit-converters/jaxb/src/main
./retrofit-converters/jaxb3/src/main
./retrofit-converters/kotlinx-serialization/src/main
./retrofit-converters/moshi/src/main
./retrofit-converters/protobuf/src/main
./retrofit-converters/scalars/src/main
./retrofit-converters/simplexml/src/main
./retrofit-converters/wire/src/main
./retrofit-mock/src/main
./retrofit-response-type-keeper/src/main
./retrofit/android-test/src/main
./retrofit/robovm-test/src/main
./retrofit/src/main
./retrofit/test-helpers/src/main
./samples/src/main
```
Note it has several subprojects. I got this autogenerated appmap.yml:
```yaml
# This is the AppMap configuration file.
# For full documentation of this file for Java programs, see:
# https://appmap.io/docs/reference/appmap-java.html#configuration
name: retrofit
packages: []
# appmap-java init looks for source packages in src/main/java.
# This folder was not found in your project, so no packages were auto-detected.
# You can add your source packages by replacing the line above with lines like this:
# packages:
# - path: com.mycorp.pkg
# - path: org.otherstuff.pkg
```
